name: Update Kubernetes Manifests

on:
  push:
  repository_dispatch:
    types: [update-manifest]

permissions:
  contents: write

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update image version in manifest
        run: |
          new_version=${{ github.event.client_payload.sha }}  # Get the sha from the payload
          sed -i "s|devopsgoofy/weather-webapp:.*|devopsgoofy/weather-webapp:${new_version}|g" manifests/deployment.yaml

      - name: Commit and push changes back to repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image version to ${new_version} [skip ci]"
          git push origin HEAD:refs/heads/main
